# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: phamthanhqb2005@gmail.com
author_name: Phucpham
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: lesson1

