# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: phamthanhqb2005@gmail.com
author_name: Phucpham
cloud_provider: vercel
contract_name: marketplace
deployment_language: python
preset_name: production
project_name: marketplace

